### PR TITLE
Fix anchor links in documentation

### PR DESCRIPTION
**Pull request by AlexWayfer**

### CODE REVIEW

**Comment by dazuma** [comment]
So this one is unclear to me. I know why we might want to make this change: because when rubydoc.info builds the documentation, it generates anchor tags of this form. However, simply running yardoc generates anchor links of the form in the current files. You can see this difference by comparing the anchor tags in [the rubydoc.info hosting](https://www.rubydoc.info/gems/toys/file/docs/guide.md) to the anchor links in [the official docs hosting](https://dazuma.github.io/toys/gems/toys/v0.9.0/file.guide.html). I don't know why rubydoc.info renders the anchor tags differently.

**Comment by AlexWayfer** [comment]
Thank you, I didn't know about official docs. 

Yes, the YARD version the same.

I found this: https://github.com/lsegal/yard/issues/1032

So, anchors are generated by Markdown library, and YARD can use one of them.

What library do you use? Can you switch it for corresponding with RubyDoc.info?

**Comment by dazuma** [comment]
Versions prior to 0.8.1 used redcarpet. More recently I switched to kramdown (for JRuby compatibility). But it didn't seem to have an effect on the anchor tags. I'll try cloning https://github.com/docmeta/rubydoc.info/ to see what it's actually doing.

**Comment by dazuma** [comment]
I tried a bunch of things, and switched back to redcarpet, and now local yard generation is producing anchors of the form generated by rubydoc.info. There are still several things I don't understand about yard's behavior, but I'm going to stop working on it now. Since I have it generating anchor IDs of your form consistently now, I'll accept this PR.

**Pull request merged**
